name: Deploy to Vercel

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Node.js 22
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build project
        run: npm run build

      # Step 5: Install Vercel CLI
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 6: Deploy to Vercel
      - name: Deploy to Production
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
